### ISSUE TITLE
KNES MRK

### ISSUE THREAD

**Issue by shinden1974** [Bellabong/RealFuels-Stock#1]
RF_Knes_MultiRoleKapsule.cfg

_Knes_mrk_Pod,_Knes_mrk_Pod_Rescue engine is pressurefed, but internal tanks are not pressurized.

**Comment by Bellabong** [comment]
I can't repeat this one :/ The tanks for all 3 of the MRK's service modules all show up as a ServiceModule to me - which supports pressure-fed engines.

**Comment by shinden1974** [comment]
Maybe a conflict on my end. Had planned on a restart/reinstall cleanup anyway, so ill close this
