### ISSUE TITLE
RF_Knes_VEGA.cfg

### ISSUE THREAD

**Issue by shinden1974** [Bellabong/RealFuels-Stock#2]
The P40 and P120C boosters don't have RealPlume configs, so they are silent with no effects ingame. I suspect it's the same way with the P120E which is in the RF_Knes_L3S.cfg.

The P80 works and it's plume config is in the ArianeV file, but the boosters I listed are not. I checked around to see if maybe the plume configs for the boosters were subject to a bracket error somewhere else, but couldn't find them at all.

didn't look like something that needed a pull request

Thank you!

**Comment by Bellabong** [comment]
Thanks for the catch! seems like RealPlumeStock didn't have configs for them so I just overlooked them.

https://github.com/Bellabong/RealFuels-Stock/commit/0cf26f035061fb61b07ac8cc9706f00f0fd81823
